#!/bin/bash -e

source map-integration-testing/ci/routing/common_functions.sh

exit_if_no_env_var TOPIC

[[ "$TOPIC" == *"FORMAT8"* ]] && MAP_CONFIG='map_format8.config'
[[ "$TOPIC" == *"NDS_OLYMPIA"* ]] && MAP_CONFIG='map_nds.config'
[[ "$TOPIC" == *"NDS_STANDARD"* ]] && MAP_CONFIG='map_nds_standard.config'
[[ "$TOPIC" == *"NDS_MOTEGI"* ]] && MAP_CONFIG='map_nds_vanilla.config'
[[ "$TOPIC" == *"NDS_BONNEVILLE"* ]] && MAP_CONFIG='map_nds_bonneville.config'
[[ "$TOPIC" == *"NDS_DONINGTON"* ]] && MAP_CONFIG='map_nds_donington.config'
[[ "$TOPIC" == *"NDS_SUPERSET"* ]] && MAP_CONFIG='map_nds_superset.config'
[[ "$TOPIC" == *"NDS_ACDC"* ]] && MAP_CONFIG='map_nds_acdc.config'
[[ "$TOPIC" == *"NDS_SPARTA_EU"* ]] && MAP_CONFIG='map/sparta/mapdb/eu.config'
[[ "$TOPIC" == *"NDS_SPARTA_NA"* ]] && MAP_CONFIG='map/sparta/mapdb/na.config'
[[ "$TOPIC" == *"NDS_SPARTA_RW"* ]] && MAP_CONFIG='map/sparta/mapdb/rw.config'

exit_if_no_env_var MAP_CONFIG

source_docker_cfg map-integration-testing/ci/routing/docker.cfg
docker pull $DOCKER_IMAGE
trap "{ [ -z $BUILD_TAG ] || docker ps -aq --filter name=$BUILD_TAG | xargs --no-run-if-empty docker rm -f --volumes || true; } &> /dev/null" EXIT
MITF_PATH=/workspace/map-integration-testing
PYTHONPATH=$MITF_PATH:$MITF_PATH/ci:$MITF_PATH/logger
MAP_CONFIG_PATH=/workspace/map-config
docker run \
    -e PYTHONPATH=$PYTHONPATH \
    --name=$BUILD_TAG \
    --interactive \
    --rm \
    --user=bldadmin \
    --volume=$WORKSPACE:/workspace \
    --workdir=/workspace \
    $DOCKER_IMAGE python3 map-integration-testing/ci/jenkins/check_existing_tests.py --map_config_path $MAP_CONFIG_PATH/$MAP_CONFIG