#!/bin/bash -xe

# The following dir should contain map-config and MITF repos you are working with:
# git clone ssh://$USER@gerrit.it.here.com:29418/mos/map-integration-testing
# git clone ssh://$USER@gerrit.it.here.com:29418/mos/map-config

export LOCAL_CODEBASE_DIR=${HOME}/here
export LOCAL_ARTIFACTS_DIR=${HOME}/artifacts

export MITF_LOCATION=${LOCAL_CODEBASE_DIR}/map-integration-testing
export MAP_CONFIG_LOCATION=${LOCAL_CODEBASE_DIR}/map-config

export MAP_PATH_PREFIX=/Users/asmirnov/new_ubuntu_vm/ # /Volumes/maps

export LDM_REGION_DVN=AU_181G0
export MODE=dev
export MAP_FORMAT=BRF
export SERVER_BUILD_JOB=psv-linux-x86-gcc7.2-release
export SERVER_BUILD_NUMBER=lastSuccessfulBuild
# SPARTA:
export CLIENT_BUILD_JOB=psv-linux-x86-gcc5.4-release-nds2.5.2
export CLIENT_BUILD_NUMBER=lastSuccessfulBuild

export WORKSPACE=/tmp/hls
rm -rf ${WORKSPACE}  # Add verification if exists
mkdir ${WORKSPACE}
mkdir -p ${LOCAL_ARTIFACTS_DIR}/${LDM_REGION_DVN}

## Unfortunately symlinks created on host do no work inside container
rsync -r --exclude .git ${MITF_LOCATION} ${WORKSPACE}
rsync -r --exclude .git ${MAP_CONFIG_LOCATION} ${WORKSPACE}

cd ${WORKSPACE}

cp ${MITF_LOCATION}/ci/routing/local/fake_report/xunit.xml ./
#cp ${LOCAL_ARTIFACTS_DIR}/routing-hls.tar.gz ./
#tar zxf routing-hls.tar.gz

bash -x ${MITF_LOCATION}/ci/routing/jenkins-commands/prod/test-data-validator
# bash -x ${MITF_LOCATION}/ci/routing/jenkins-commands/dev-env/test-acceptance-mitf-dev
# bash -x ${MITF_LOCATION}/ci/routing/jenkins-commands/prod/push-acc-tests