#!/usr/bin/env bash
set -xe

# Check mandatory variables
source map-integration-testing/ci/routing/common_functions.sh
exit_if_no_env_var LDM_REGION_DVN
set_env_var_if_not_set SOURCE_DATA_PATH ${WORKSPACE%/*}/acc-test-data-preparation-pipeline/LDM

DB_PATH=${SOURCE_DATA_PATH}/${LDM_REGION_DVN}

if [[ -d ${DB_PATH} ]]; then
    echo "INFO: Removing ${LDM_REGION_DVN} LDM DBs from slave storage..."
    rm -rf ${DB_PATH}
    if [[ ${?} -eq 0 ]]; then
        echo "INFO: ${LDM_REGION_DVN} LDM DBs have been successfully removed"
    else
        echo "ERROR: ${LDM_REGION_DVN} LDM DBs have NOT been removed!"
    fi
else
    echo "WARNING: ${LDM_REGION_DVN} LDM does not exist on slave storage"
fi
