#!/usr/bin/env bash
set -xe

# Check mandatory variables
source map-integration-testing/ci/routing/common_functions.sh
exit_if_no_env_var MAP_FORMAT
set_env_var_if_not_set USE_CACHE True

if [[ ${MAP_FORMAT} == "F8" ]]; then
    MAP_CONFIG="map_format8.config"
    # Read Map Config file
    source ${WORKSPACE}/map-config/${MAP_CONFIG}
    MAP_VERSION=${map_version}
    MAP_BUCKET=${map_aws_s3_bucket_url}
    MAP_OBJECT_KEY=${file_world_cdt}
    MAP_PATH=${map_path}
    # Redefine local Jenkins storage path
    F8_MAP_PATH=${WORKSPACE%/*}/acc-test-data-preparation-pipeline/F8
    LOCAL_MAP_PATH=${F8_MAP_PATH_PREFIX}/${MAP_PATH}
elif [[ ${MAP_FORMAT} == "BRF" ]] || [[ ${MAP_FORMAT} == "OLS" ]]; then
    # Read BRF Config file
    BRF_CONFIG="map_format8_brf.config"
    source ${WORKSPACE}/map-config/${BRF_CONFIG}
    MAP_VERSION=${map_version}
    BRF_VERSION=${brf_compiler_version}
    MAP_BUCKET=${map_aws_s3_bucket_url}
    MAP_OBJECT_KEY=${folder_routing_server_brf}
    # Redefine local Jenkins storage path
    BRF_MAP_PATH=${WORKSPACE%/*}/acc-test-data-preparation-pipeline/BRF
    LOCAL_MAP_PATH=${BRF_MAP_PATH}/${MAP_OBJECT_KEY}
else
    echo "ERROR: Unsupported MAP_FORMAT: ${MAP_FORMAT}"
    exit 1
fi

# Format AWS S3 Map path
S3_MAP_PATH=${MAP_BUCKET}/${MAP_OBJECT_KEY}
echo "INFO: Map Version [${MAP_VERSION}] will be downloaded from AWS S3 ${S3_MAP_PATH} to the ${LOCAL_MAP_PATH} Jenkins local storage"

if [[ ! -d ${LOCAL_MAP_PATH} ]]; then
    echo "INFO: Map: ${MAP_VERSION} version will be downloaded"
    echo "WARN: Previous map will be removed"
    #TODO: Hard coded for HLS only
    rm -rf ${BRF_MAP_PATH}/*
else
    if [[ ${USE_CACHE} == "True" ]]; then
        echo "INFO: Download is not needed. Cached Map: ${MAP_VERSION} version will be used!"
        exit 0
    elif [[ ${USE_CACHE} == "False" ]]; then
        echo "WARNING: Force downloading ... Cached Map: ${MAP_VERSION} version will be used!"
        rm -rf ${LOCAL_MAP_PATH}
    fi
fi

# Copy LDM S3 objects to the local Jenkins storage
aws s3 cp ${S3_MAP_PATH} ${LOCAL_MAP_PATH} --recursive --force-glacier-transfer
