#!/usr/bin/env bash
set -xe

# Check mandatory variables
source map-integration-testing/ci/routing/common_functions.sh
exit_if_no_env_var LDM_REGION_DVN
set_env_var_if_not_set SOURCE_DATA_PATH ${WORKSPACE%/*}/acc-test-data-preparation-pipeline/LDM
set_env_var_if_not_set USE_CACHE true

check_ldm_name ${LDM_REGION_DVN}
if [[ ${STATUS} == 0 ]]; then
    echo "ERROR: Further processing does not make sense . Exiting..."; exit 1
fi

DB_PATH=${SOURCE_DATA_PATH}/${LDM_REGION_DVN}

if [[ ${USE_CACHE} == "true" ]] && [[ -d ${DB_PATH} ]]; then
    echo "INFO: Download is not needed. Cached LDM: ${LDM_REGION_DVN} DBs will be used!"
    exit 0
elif [[ ${USE_CACHE} == "false" ]] && [[ -d ${DB_PATH} ]]; then
    echo "WARNING: Force downloading ... Cached LDM: ${LDM_REGION_DVN} DBs will be removed"
    rm -rf ${DB_PATH}
elif [[ ! -d ${DB_PATH} ]]; then
    echo "INFO: ${LDM_REGION_DVN} DBs have not exists yet. Downloading ..."
    mkdir -p ${DB_PATH}
else
    echo "ERROR: Please check Job's parameters. (USE_CACHE: ${USE_CACHE} -> should be [true, false])"
fi

# Copy LDM S3 objects to the local Jenkins storage
aws s3 cp s3://${LDM_BUCKET}/${LDM_KEY_PREFIX}/${LDM_REGION_DVN} ${DB_PATH} --recursive \
                                                                            --force-glacier-transfer
