#!/usr/bin/env bash
set -xe

# Check mandatory variables
source map-integration-testing/ci/routing/common_functions.sh
exit_if_no_env_var LDM_REGION_DVN
set_env_var_if_not_set SOURCE_DATA_PATH ${WORKSPACE%/*}/acc-test-data-preparation-pipeline/LDM

# Docker preparation and execution
source_docker_cfg map-integration-testing/ci/routing/docker.cfg
docker pull ${DOCKER_IMAGE} && exception_docker "${BUILD_TAG}"

docker run --env LDM_REGION_DVN=${LDM_REGION_DVN} \
           --env SOURCE_DATA_PATH=${SOURCE_DATA_PATH} \
           --env MITF_PATH="/workspace" \
           --env AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}   \
           --env BUCKET=${MITF_ARTIFACTS_BUCKET} \
           --interactive \
           --name=${BUILD_TAG} \
           --rm \
           --user="bldadmin" \
           --volume=${SOURCE_DATA_PATH}:${SOURCE_DATA_PATH}:rw \
           --volume=${WORKSPACE}:/workspace \
           --workdir="/workspace" \
           ${DOCKER_IMAGE} map-integration-testing/ci/routing/acceptance/generate_acc_tests.sh ${DESIRED_TC_QTY} \
                                                                                               ${GENERATORS}

# Upload generated dumps to S3 and put object ACL
aws s3 cp ${WORKSPACE}/tests.tgz s3://${MITF_ARTIFACTS_BUCKET}/mitf/acc/${LDM_REGION_DVN}/ &&
aws s3api put-object-acl --bucket ${MITF_ARTIFACTS_BUCKET} \
                         --key mitf/acc/${LDM_REGION_DVN}/tests.tgz \
                         --grant-full-control ${MITF_AWS_S3_GRANTS}
